name: base
channels:
  - conda-forge
  - intel
  - ccpi
  - defaults
dependencies:
  - jupyterlab
  - jupyter
  - ipywidgets<8 # vis. https://github.com/TomographicImaging/CIL/pull/1599
  - widgetsnbextension
  - nodejs
