name: base
channels:
  - conda-forge
  - intel # cil
  - ccpi  # cil
  - defaults
dependencies:
  - setuptools
  - wheel
  - pytest
  - pytest-cov
  - scipy
  - docopt
  - matplotlib
  - pandas
  - tifffile
  - nibabel
  - deprecation
  - nose
  - pip
  - cil              # cil
  - ccpi-regulariser # cil
  # - tigre          # cil (GPU)
  # - astra-toolbox  # cil (GPU)
  - pip:
    - git+https://github.com/data-exchange/dxchange.git # cil
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools
