name: base
channels:
  - conda-forge
  - intel
  - ccpi
  - defaults
dependencies:
  - mamba
  - setuptools
  - wheel
  - pytest
  - pytest-cov
  - numpy        # CIL
  - scipy
  - docopt
  - matplotlib
  - Cython       # CIL
  - h5py         # CIL
  - Pillow       # CIL
  - wget         # CIL
  - six          # CIL
  - olefile      # CIL
  - opencv       # CIL
  - numba        # CIL
  - pandas
  - tifffile
  - nibabel
  - deprecation
  - nose
  - ipp          # CIL
  - ipp-devel    # CIL
  - ipp-include  # CIL
  - tigre=2.4    # CIL
  - pip
  - pip:
    - git+https://github.com/data-exchange/dxchange.git  # CIL
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools
