name: base
channels:
  - conda-forge
  - intel
  - ccpi
  - astra-toolbox
  - defaults
dependencies:
  - numpy=1.22
  - scikit-image
  - pytorch
  - torchvision
  - ipywidgets<8
  - astra-toolbox
  - tigre=2.4
  - dxchange
  - pip:
    - brainweb  # CIL
    - cuqipy-cil
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools
    
