name: base
channels:
  - conda-forge
  - intel
  - ccpi
  - defaults
dependencies:
  - scikit-image
  - pytorch
  - torchvision
  - pip:
    - brainweb  # CIL
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools